# Generated by Django 4.1.7 on 2023-02-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="user",
            new_name="site",
        ),
    ]
