# Generated by Django 4.1.7 on 2023-02-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0002_rename_user_page_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_num", models.CharField(max_length=10)),
                ("msg", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="page",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
