# Generated by Django 4.1.7 on 2023-02-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0005_delete_urls_logs_serial_num_page_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="URLs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name="logs",
            name="serial_num",
        ),
        migrations.RemoveField(
            model_name="page",
            name="site",
        ),
    ]
