# Generated by Django 4.1.7 on 2023-02-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0006_urls_remove_logs_serial_num_remove_page_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="url",
            field=models.CharField(max_length=500),
        ),
    ]
