# Generated by Django 4.1.7 on 2023-02-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0007_alter_page_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urls",
            name="url",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
